data:
  fewshot_maxsize: 4
  label_path: "../../Data/GSM8K.tsv"

retriver:
  input_dim: 1536
  hidden_dim: 64

llm_agent:
  model_name: gpt-4o-mini

general:
  back_every_steps: 2
  experiment_name: 'gsm8k-gpt-4o-mini-promptpg-maxlen-4-0802'

train:
  n_epochs: 20
  batch_size: 256
  learning_rate: 0.001
  

valid:
  batch_size: 2056