data:
  fewshot_set: 'mix'
  fewshot_maxsize: 4
  label_path: "../../Data/MathKnowCT.tsv"

retriver:
  input_dim: 1536
  hidden_dim: 64

llm_agent:
  model_name: mistralai/Mistral-Large-Instruct-2407
  batch_size: 8

general:
  back_every_steps: 2
  experiment_name: 'mistral-large-promptpg-maxlen-4-0925-mix'

train:
  n_epochs: 20
  batch_size: 256
  learning_rate: 0.001
  

valid:
  batch_size: 2056