data:
  fewshot_set: 'mix'
  fewshot_maxsize: 2
  label_path: "../../Data/data.tsv"

retriver:
  input_dim: 1536
  hidden_dim: 64

llm_agent:
  model_name: mistralai/Mistral-7B-Instruct-v0.2
  batch_size: 8

general:
  back_every_steps: 2
  experiment_name: 'mistral-7b-promptpg-maxlen-2-0514-mix'

train:
  n_epochs: 20
  batch_size: 256
  learning_rate: 0.001
  

valid:
  batch_size: 2056